### ISSUE TITLE
redis密码中包含#时无法处理

### ISSUE THREAD

**Issue by githahaha** [TraceNature/redissyncer-server#102]
版本: syncer-webapp-3.3.3.3-with-frontend.jar
经测试, redis密码中包含#时无法创建任务.

**Comment by pingxingshikong** [comment]
3.3.3.8已修复
https://github.com/TraceNature/redissyncer-server/releases/tag/3.3.3.8

**Comment by wwtao1024** [comment]
还是有问题 只要包含特殊字符就有问题

**Comment by wwtao1024** [comment]
&*(!@#
