### ISSUE TITLE
未同步成功

### ISSUE THREAD

**Issue by incubus-ohy** [TraceNature/redissyncer-server#50]
![image](https://user-images.githubusercontent.com/40196468/119642088-f01a9d00-be4c-11eb-9a1a-45f9477fd9c1.png)
![image](https://user-images.githubusercontent.com/40196468/119642195-0b85a800-be4d-11eb-8f6e-e640c7cfb9c8.png)
![image](https://user-images.githubusercontent.com/40196468/119642196-0b85a800-be4d-11eb-9982-f7d07464d3ca.png)

未同步数据，
尝试了单点同步单点、集群同步单点

**Comment by pingxingshikong** [comment]
能否把详细的日志文件发一下？

**Comment by incubus-ohy** [comment]
您好，我创建了2个到单节点作为测试，这是全部的日志
![image](https://user-images.githubusercontent.com/40196468/119756217-cf4a5a00-bed5-11eb-94cb-282621dba530.png)
![image](https://user-images.githubusercontent.com/40196468/119756255-dffad000-bed5-11eb-9819-8c4025c2392e.png)

**Comment by incubus-ohy** [comment]
不好意思，我没有看到有dbMapper的映射，已经成功了，感谢您的开源
