### ISSUE TITLE
redissyncer-server 是否支持主备模式

### ISSUE THREAD

**Issue by zeekling** [TraceNature/redissyncer-server#52]
如题，一般生产环境要求都比较搞，会使用主备模式，redissyncer-server是否支持模式部署。

**Comment by jiashiwen** [comment]
主备模式在任务模型上不是一个好选择，我们正在尝试分布式任务调度解决生产环境的高可用问题。

**Comment by zeekling** [comment]
> 主备模式在任务模型上不是一个好选择，我们正在尝试分布式任务调度解决生产环境的高可用问题。

嗯，我觉得分布式多主这种可能是最好的选择了。

**Comment by zeekling** [comment]
我把这个关了吧
