### ISSUE TITLE
增量同步MULTI命令会报错

### ISSUE THREAD

**Issue by yuddpky** [TraceNature/redissyncer-server#53]

**Comment by pingxingshikong** [comment]
能否发一下对应的报错日志和syncer版本

**Comment by yuddpky** [comment]
开源Cluster5.0
Cluster ——> Cluster
redissyncer用的3.1.0_release
![image](https://user-images.githubusercontent.com/8911561/125906110-baf4a723-5629-4334-abb9-933f8e73fe24.png)
![image](https://user-images.githubusercontent.com/8911561/125906259-64f17614-d53c-4ab9-af36-83f14d593451.png)
dc.getArgs() 没有值导致

**Comment by yuddpky** [comment]
MULTI不需要计算solt

**Comment by pingxingshikong** [comment]
因为cluster模式的事务不支持跨节点key，有很大的局限性，jedis中没有实现对应接口,我们会在近期扩展目标为在cluster下对于MULTI命令的支持

**Comment by pingxingshikong** [comment]
https://github.com/TraceNature/redissyncer-server/releases/tag/3.1.0.1 
3.1.0.1版本中已经修复了这个问题
