### ISSUE TITLE
双向复制的功能可用了吗？

### ISSUE THREAD

**Issue by susongyan** [TraceNature/redissyncer-server#59]
看目前最新的代码
辅助key的任务
RedisMultiSyncBreakingRingByAuxiliaryKeyTransmissionTask 还没有提供使用   

我这边想通过这种辅助key的方式做双向复制任务，请问这块的功能 完成了吗？

**Comment by pingxingshikong** [comment]
双向同步会涉及到很多问题，利用辅助key实现双向同步是一个探索性的验证,我们目前只做了数据破环方面的实验，目前还没有去完整的实现这块的功能。

**Comment by susongyan** [comment]
> 双向同步会涉及到很多问题，利用辅助key实现双向同步是一个探索性的验证,我们目前只做了数据破环方面的实验，目前还没有去完整的实现这块的功能。

涉及到的问题主要是没法去做crdt 冲突处理吗？  这个我这边暂时考虑不了， 没去改redis源码的能力和时间； 
主要需求是单向的迁移能力，以及双向的实时复制，  对我这边来说：原则上同一个key也不应该再两个机房都去操作  这块双向冲突的场景较少 暂时不考虑数据的冲突，  考虑是后续校验发现不一致 告警处理

顺着RedisMultiSyncBreakingRingByAuxiliaryKeyTransmissionTask的思路 改了下代码   复制环破成功了；其他细节问题根据实际的一步步去处理吧， 比如复制到cluster时 psetex auxkey;  set normal key  这两个得在目标集群同一个节点才能保证 反向任务先收到 psetex auxkey 去做破环的前置缓存 

目前主要是缺少 portal把 孤立的task节点 给管理调度起来，这块开发

**Comment by pingxingshikong** [comment]
是的，分片集群模式auxkey可以直接使用normal key的crc16或者修改auxkey的生成规则使auxkey和normal key 的crc16一致,只要能够保证将辅助key和正常key写入同一个分片就可以。因为auxkey只参与破环，所以在写入auxkey和正常key时可以把cluster的每个分片当作单节点看，第一种方式可以先计算正常key的crc16,再将auxkey直接写入正常key所属的分片。

**Comment by susongyan** [comment]
> 是的，分片集群模式auxkey可以直接使用normal key的crc16或者修改auxkey的生成规则使auxkey和normal key 的crc16一致,只要能够保证将辅助key和正常key写入同一个分片就可以。因为auxkey只参与破环，所以在写入auxkey和正常key时可以把cluster的每个分片当作单节点看，第一种方式可以先计算正常key的crc16,再将auxkey直接写入正常key所属的分片。

嗯，可以基于jedis 的JedisClusterCRC16.getSlot计算，然后 getConnectionFromSlot 去执行

**Comment by susongyan** [comment]
想想还是基于hashtag的好点，  万一遇到cluster扩缩容 aux key就不知道去哪里了

**Comment by susongyan** [comment]
全量的ValueDumpIterableRdbParser  一定要配合 ValueDumpIterableEventListener  这个监听器来使用吗？  
我直接new EventListener的话， 如果源集群里边有 list类型，全量的阶段会报错

2021-09-03 21:20:03.761|[ERROR]|[threadPoolTaskExecutor-9] -> SocketReplication#open:123 | TASKID[59DC2A4F4BF947718958B3053A254589] error reason unexpected value type:108, check your ModuleParser or ValueIterableRdbVisitor.

**Comment by pingxingshikong** [comment]
ValueDumpIterableEventListener是EventListener 的实现类,是和ValueDumpIterableRdbParser全量命令解析器对应的，目前为了方便同步ValueDumpIterableRdbParser解析器除了list、hash 、set等可能存在大key的数据类型，其他的都是走的dump restore序列化的形式，你也可以自己去实现一个EventListener和RdbParser来决定全量阶段的数据解析成什么类型,一般要么是正常命令的形式，要么序列化类型的，但是要是解析成dump restore类型的需要知道对方的rdb version

**Comment by pingxingshikong** [comment]
> 全量的ValueDumpIterableRdbParser 一定要配合 ValueDumpIterableEventListener 这个监听器来使用吗？
> 我直接new EventListener的话， 如果源集群里边有 list类型，全量的阶段会报错
> 
> 2021-09-03 21:20:03.761|[ERROR]|[threadPoolTaskExecutor-9] -> SocketReplication#open:123 | TASKID[59DC2A4F4BF947718958B3053A254589] error reason unexpected value type:108, check your ModuleParser or ValueIterableRdbVisitor.

这个错误是rdb解析器没有命中现有的命令类型，你可以看下前方有没有 replicationHandler.setRdbParser(new ValueDumpIterableRdbParser(replicationHandler, rdbVersion))设置全量命令解析器

**Comment by susongyan** [comment]
应该是的     我直接基于 replicator的 dumpRdbPaser 弄了； 双向 全量的时候 list、set这类不能去切大key   会导致两边子元素重复
用dump key + restore 覆盖靠谱些
