### ISSUE TITLE
能否支持双主实时双向同步？

### ISSUE THREAD

**Issue by penweizgx** [TraceNature/redissyncer-server#73]
测试了一下建了两个任务a->b 和 b->a，都启动全量同步,会导致两边循环发送，数据错乱

**Comment by pingxingshikong** [comment]
命令循环发送需要破环，可以通过辅助key去实现命令破环。双向同步会涉及到很多问题，利用辅助key实现双向同步目前只做了探索性的验证,我们目前只做了数据破环方面的实验，目前还没有去完整的实现这块的功能。
