### ISSUE TITLE
rdb过程中，string类型数据，用append会导致数据不一致吧

### ISSUE THREAD

**Issue by chenqi14** [TraceNature/redissyncer-server#76]
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/37201487/165913154-fe27cb42-828c-432d-af23-0691104e0b1e.png">

如果目标集群中已经有相同key的情况下，这时候append会导致数据与源端不一致吧

**Comment by pingxingshikong** [comment]
默认string类型是走的dump restore形式 ，这是大key拆分的情况才会进行拆分去 append合并

**Comment by chenqi14** [comment]
> 分
那如果是大key的情况，用append还是会与源端不一致吧

**Comment by pingxingshikong** [comment]
理论上迁移场景，目标库不会存在相同的key，如果目标集群中已经有相同key的情况下，需要选择覆盖还是抛弃源端的同名key，因为如果目标端有同名key肯定会产生数据不一致的情况

**Comment by chenqi14** [comment]
好嘞，谢谢大佬
