### ISSUE TITLE
为啥kafka模式的rdb解析比其他模式慢很多

### ISSUE THREAD

**Issue by chenqi14** [TraceNature/redissyncer-server#77]
对比了一下目标端是kafka与redis的情况，发现kafka模式很慢，原先几秒就能同步完的任务，kafka要几十分钟

**Comment by chenqi14** [comment]
这个原因找到了，kafka的rdb解析器对string类型的解析和其他模式不一样，同步的源redis集群中的数据大多都是string类型。

**Comment by pingxingshikong** [comment]
kafka string不会走dump模式，因为dump命令需要知道目标redis的rdb版本，所以string类型会解析成set key value这种格式

**Comment by chenqi14** [comment]
>

**Comment by chenqi14** [comment]
好的，redis目标端的版本我这边确定的，所以可以改成dump的吧
