### ISSUE TITLE
3.3.3版本在内网复制验证过程中，发现同步延迟固定3s，请问是为什么呢？有什么配置参数可以调整么？

### ISSUE THREAD

**Issue by chenruiyingry** [TraceNature/redissyncer-server#86]

**Comment by pingxingshikong** [comment]
因为是通过pipeline批量写入的，没有达到提交key的数量的话会每3s写入，这个参数目前没有暴露出来，可以修改下代码里的写入间隔或者每个批次的提交count，重新编译一下就可以了
https://github.com/TraceNature/redissyncer-server/blob/main/syncer-transmission/src/main/java/syncer/transmission/client/impl/JedisPipeLineClient.java

**Comment by chenruiyingry** [comment]
好的，谢谢
