### ISSUE TITLE
RDB文件同步数据异常

### ISSUE THREAD

**Issue by 907198504** [TraceNature/redissyncer-server#93]
使用本地RDB数据文件同步成功，但是数据和源数据不一致，如下图：
![image](https://github.com/TraceNature/redissyncer-server/assets/29398937/04657f13-bc66-4b45-904e-06ae4e118e74)

redissyncer-server版本：3.3.3.1
源Redis版本：6.2.6
目标Redis版本：6.2.6

**Comment by 907198504** [comment]
rdb文件：
[dump.rdb.zip](https://github.com/TraceNature/redissyncer-server/files/12866977/dump.rdb.zip)

**Comment by pingxingshikong** [comment]
本地rdb文件导入 string类型value为数字字符串时会导致不一致的情况，3.3.3.3 已修复
