### ISSUE TITLE
源集群和目标集群都是 sentinel 模式，同步任务应该怎样配置？

### ISSUE THREAD

**Issue by stardustman** [TraceNature/redissyncer-server#95]
源集群和目标情况：
1 master，2 replicas，3 sentinel 。
创建任务时需要怎样配置？
<img width="1328" alt="image" src="https://github.com/TraceNature/redissyncer-server/assets/22998204/a5f814ec-a0ab-4aa2-8f60-9aafbd0b858b">

**Comment by pingxingshikong** [comment]
源端主节点和从节点都可以，目标段需要主节点

**Comment by pingxingshikong** [comment]
3.x暂时不支持填sentinel节点，目标端直接填当前的主机节点就行，4.x会支持

**Comment by stardustman** [comment]
> 3.x暂时不支持填sentinel节点，目标端直接填当前的主机节点就行，4.x会支持
如果不是在 web 页面上添加，直接使用代码的方式可以通过配置原集群的 sentinel 和目标集群的 sentinel 同步么？
